openapi: 3.0.0
info:
  version: 1.0.0
  title: Nidus
  description: Home Automation and Monitoring.
  license:
    name: MIT
  contact:
    name: Alexandre Lamberty
    email: mail@alexandrelamberty.com
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
paths:
  /pets: {}
  /pets/{petId}: {}
